apiVersion: v1
kind: Service
metadata:
  name: php-staging
  labels:
    tier: backend-staging
spec:
  selector:
    app: php-staging
    tier: backend-staging
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-staging
  labels:
    tier: backend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-staging
      tier: backend-staging
  template:
    metadata:
      labels:
        app: php-staging
        tier: backend-staging
    spec:
      containers:
      - name: php-staging
        image: x3nomorpheus/api
      securityContext: 
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0" 
