apiVersion: v1
kind: Service
metadata:
  name: react-staging
  labels:
    tier: front-staging
spec:
  selector:
    app: react-staging
    tier: front-staging
  ports:
  - protocol: TCP
    port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-staging
  labels:
    tier: front-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-staging
      tier: front-staging
  template:
    metadata:
      labels:
        app: react-staging
        tier: front-staging
    spec:
      containers:
      - name: react-staging
        image: x3nomorpheus/front
        imagePullPolicy: Always
