apiVersion: v1
kind: Service
metadata:
  name: redis-staging
spec:
  selector:
    run: redis-staging
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-staging
spec:
  selector:
    matchLabels:
      run: redis-staging
  replicas: 1
  template:
    metadata:
      labels:
        run: redis-staging
    spec:
      containers:
        - name: redis-staging-container
          image: x3nomorpheus/redis
          resources:
            limits:
              cpu: "70m"
              memory: "512Mi"
            requests:
              cpu: "40m"
              memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-staging-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-staging
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
