apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
      environment: production 
  type: LoadBalancer
  ports:
    - name: prometheus
      port: 8080
      targetPort: 9090 
    - name: alertmanager
      port: 9093
      targetPort: 9093
    - name: grafana
      port: 3000
      targetPort: 3000
