apiVersion: v1
kind: Service
metadata:
  name: production-lb
spec:
  selector: 
    env: prod
  type: LoadBalancer  
  ports:
    - port: 8080
      targetPort: 5601
    - port: 80
      targetPort: 80 
