apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
  selector:
    app: nginx
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: x3nomorpheus/nginx
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 20m
          command: ["sh", "-c"]
          args:
            - while [ 1 ]; do
              echo "Test";
              sleep 0.01;
              done
