apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    tier: front
spec:
  selector:
    app: react
    tier: front
  ports:
  - protocol: TCP
    port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
      tier: front
  template:
    metadata:
      labels:
        app: react
        tier: front
    spec:
      containers:
      - name: react
        image: x3nomorpheus/front
