apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: prod
  template:
    metadata:
      labels:
        app: nginx
        env: prod
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: x3nomorpheus/nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
	resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
