apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
   labels:
     app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: x3nomorpheus/nginx
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
   app: nginx
